import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'cs' | 'en' | 'de';
export type Currency = 'CZK' | 'EUR';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  currency: Currency;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  cs: {
    // Navigation
    'nav.home': 'Domů',
    'nav.athletes': 'Pro sportovce',
    'nav.employers': 'Pro zaměstnavatele',
    'nav.pricing': 'Ceník',
    'nav.contact': 'Kontakt',
    'nav.blog': 'Příběhy',
    'nav.login': 'Přihlásit se',
    'nav.signup': 'Registrace',

    // Hero
    'hero.headline': '98 % českých sportovců nikdy nepůjde do profi.',
    'hero.headline2': 'My jim dáváme kariérní restart.',
    'hero.subheadline': 'První pracovní portál v České republice, který propojuje sportovní talent s reálnými pracovními příležitostmi.',
    'hero.cta.athlete': 'Vytvořit profil zdarma',
    'hero.cta.employer': 'Najít sportovní talenty',

    // Story section
    'story.title': 'Když skončí sport, život nekončí.',
    'story.paragraph1': 'Tomáš trénoval šest dní v týdnu. Zranění rozhodlo za něj.',
    'story.paragraph2': 'Eliška vedla tým jako kapitánka. Po kariéře slyšela, že „nemá praxi".',
    'story.paragraph3': 'Talent Restart vznikl proto, aby sportovci nemuseli začínat od nuly.',
    'story.paragraph4': 'Disciplína, vytrvalost a odpovědnost mají hodnotu i mimo stadion.',

    // Pricing
    'pricing.title': 'Ceník pro zaměstnavatele',
    'pricing.subtitle': 'Vyberte si plán, který vám vyhovuje',
    'pricing.standard': 'Standard Pack',
    'pricing.pro': 'Pro Pack',
    'pricing.monthly': 'měsíčně',
    'pricing.yearly': 'ročně',
    'pricing.perMonth': 'měsíc',
    'pricing.perYear': 'rok',
    'pricing.cta': 'Začít nyní',
    'pricing.features.jobs': 'Neomezené nabídky práce',
    'pricing.features.applicants': 'Přístup k profilům sportovců',
    'pricing.features.ai': 'AI asistent pro popisy práce',
    'pricing.features.support': 'Prioritní podpora',
    'pricing.features.analytics': 'Pokročilá analytika',
    'pricing.features.branding': 'Firemní branding',

    // Contact
    'contact.title': 'Kontaktujte nás',
    'contact.subtitle': 'Máte dotaz? Rádi vám pomůžeme.',
    'contact.name': 'Jméno a příjmení',
    'contact.email': 'E-mail',
    'contact.phone': 'Telefon',
    'contact.role': 'Jsem',
    'contact.role.employer': 'Zaměstnavatel',
    'contact.role.athlete': 'Sportovec',
    'contact.role.club': 'Klub',
    'contact.role.university': 'Univerzita',
    'contact.role.other': 'Jiné',
    'contact.organization': 'Název organizace',
    'contact.subject': 'Předmět',
    'contact.subject.hiring': 'Nábor',
    'contact.subject.partnership': 'Partnerství',
    'contact.subject.support': 'Podpora',
    'contact.subject.general': 'Obecný dotaz',
    'contact.message': 'Zpráva',
    'contact.gdpr': 'Souhlasím se zpracováním osobních údajů',
    'contact.submit': 'Odeslat zprávu',
    'contact.success': 'Děkujeme za zprávu. Ozveme se vám co nejdříve.',

    // Login
    'login.subtitle': 'Přihlaste se ke svému účtu',
    'login.email': 'E-mail',
    'login.password': 'Heslo',
    'login.submit': 'Přihlásit se',
    'login.noAccount': 'Nemáte účet?',
    'login.signupLink': 'Zaregistrujte se',

    // Signup
    'signup.subtitle': 'Vytvořte si nový účet',
    'signup.athlete': 'Sportovec',
    'signup.employer': 'Zaměstnavatel',
    'signup.firstName': 'Jméno',
    'signup.lastName': 'Příjmení',
    'signup.email': 'E-mail',
    'signup.password': 'Heslo',
    'signup.confirmPassword': 'Potvrdit heslo',
    'signup.submitAthlete': 'Vytvořit profil sportovce',
    'signup.submitEmployer': 'Vytvořit účet zaměstnavatele',
    'signup.hasAccount': 'Již máte účet?',
    'signup.loginLink': 'Přihlaste se',

    // Footer
    'footer.rights': 'Všechna práva vyhrazena.',


    // Theme
    'theme.light': 'Denní režim',
    'theme.dark': 'Noční režim',

    // Dashboard
    'dash.header': 'Dashboard',
    'dash.premium': 'Premium aktivní',
    'dash.demand': 'Vysoká poptávka na trhu',
    'dash.session': 'Relace',
    'dash.proAccount': 'Pro účet',
    'dash.freeAccount': 'Bezplatný účet',
    'dash.availableAthletes': 'Dostupní sportovci',
    'dash.missedOps': 'Zmeškané příležitosti',
    'dash.compsFaster': 'Konkurence je rychlejší.',
    'dash.advAnalytics': 'Pokročilá analytika',
    'dash.premAnalytics': 'Premium analytika',
    'dash.unlockData': 'Odemknout data',
    'dash.viewReports': 'Zobrazit reporty',
    'dash.recommendations': 'Top doporučení',
    'dash.viewAll': 'Zobrazit vše',
    'dash.recRisk': 'Riziko náboru',
    'dash.high': 'VYSOKÉ',
    'dash.riskDesc': 'Vaše současná "pasivní" strategie má na tomto trhu 80% chybovost.',
    'dash.marketSpeed': 'Rychlost trhu',
    'dash.critical': 'Kritická',
    'dash.strategyActive': 'Strategie aktivní',
    'dash.switchAggressive': 'Přepnout na agresivní',
    'dash.missingPotential': 'Přicházíte o 85 % kandidátů.',
    'dash.upgradeNow': 'Upgradovat nyní',
    'dash.limit': 'Limit bezplatného plánu',
    'dash.overview': 'Přehled',
    'dash.pipeline': 'Talent Pipeline',
    'dash.messages': 'Zprávy',
    'dash.history': 'Historie',
    'dash.marketIntel': 'Tržní informace',
    'dash.compWatch': 'Sledování konkurence',
    'dash.riskAnalysis': 'Analýza rizik',
    'dash.nextSteps': 'Vaše další kroky',
    'dash.completeCv': 'Dokončit CV',
    'dash.addAchiev': 'Přidejte své úspěchy',
    'dash.aiTrans': 'AI překlad',
    'dash.convSkills': 'Převést sportovní dovednosti',
    'dash.browseJobs': 'Hledat práci',
    'dash.newMatches': '3 nové shody',
    'dash.recReads': 'Doporučené čtení',
    'dash.mostPop': 'Nejoblíbenější',
    'dash.futureLeader': 'Budoucí lídr byznysu',
    'dash.profileStr': 'Síla profilu',
    'dash.topCandidate': 'Jste mezi top 10 % kandidátů!',
    'dash.proTip': 'Pro Tip',
    'dash.proTipDesc': '"V byznysu, stejně jako ve sportu, je regenerace klíčová. Nevyhořte před fází pohovorů."',
    'dash.readMore': 'Číst více',
    'header.myCareer': 'Moje Kariéra',
    'header.overview': 'Přehled',
    'header.careerTips': 'Kariérní Tipy',
    'header.loggedInAs': 'Přihlášen jako',
    'header.myProfile': 'Můj Profil',
    'header.logout': 'Odhlásit se',
    'footer.athletes': 'Pro Sportovce',
    'footer.createProfile': 'Vytvořit profil',
    'footer.careerAdvice': 'Kariérní poradenství',
    'footer.athleteStories': 'Příběhy sportovců',
    'footer.employers': 'Pro Firmy',
    'footer.businessSolutions': 'Firemní řešení',
    'footer.contact': 'Kontakt',
    'footer.location': 'Praha, Česká republika',
    'footer.desc': 'První platforma v ČR propojující disciplínu sportovců s příležitostmi ve světě byznysu.',
    'index.hero.athletePath': 'Vaše kariérní cesta',
    'index.hero.welcomeBack': 'Vítejte zpět',
    'index.hero.nextChallenge': 'Vaše příští výzva čeká',
    'index.hero.discoverTalents': 'Objevte další talenty',
    'index.hero.strength': 'Profil síla',
    'index.hero.newMatches': 'Nové shody',
    'index.hero.views': 'Zobrazení',
    'index.howItWorks': 'Jak to funguje',
    'index.simpleProcess': 'Jednoduchý proces pro sportovce i zaměstnavatele',
    'index.successStories': 'Příběhy úspěšných',
    'index.storyDesc': 'Inspirujte se sportovci, kteří už svůj restart úspěšně zvládli.',
    'index.allStories': 'Všechny příběhy',
    'index.readyStart': 'Připraveni na nový začátek?',
    'index.joinThousands': 'Připojte se k tisícům sportovců, kteří našli novou kariéru díky Talent Restart.',
    'athletes.hero.newStart': 'Váš nový začátek',
    'athletes.hero.careerValue': 'Vaše sportovní kariéra',
    'athletes.hero.enormousValue': 'má obrovskou hodnotu',
    'athletes.whyRestart': 'Proč zvolit Talent Restart?',
    'athletes.notJustCv': 'S námi nepíšete jen životopis, ale vyprávíte příběh svého úspěchu.',
    'athletes.medals': 'Vaše medaile neumíme vystavit.',
    'athletes.translate': 'Ale umíme je přeložit.',
    'athletes.aiDesc': 'Náš pokročilý AI algoritmus analyzuje vaši sportovní historii a automaticky ji transformuje do jazyka, kterému rozumí HR manažeři a CEO.',
    'athletes.beta': 'Vyzkoušet AI asistenta (Beta)',
    'pricing.transparent': 'Transparentní Ceny',
    'pricing.athletesFree': 'Sportovci mají vždy 100% přístup ZDARMA',
    'pricing.popular': 'Nejoblíbenější',
    'pricing.noFees': 'Žádné skryté poplatky',
    'pricing.secure': 'Bezpečné platby',
    'pricing.support': 'Špičková podpora',
    'pricing.instant': 'Okamžitý přístup',
    'pricing.fair': 'Férové podmínky',
    'jobs.browse': 'Hledat práci',
    'jobs.matches': 'Shody',
    'jobs.multiplier': 'Pozice, kde vaše sportovní disciplína funguje jako multiplikátor.',
    'jobs.filters': 'Filtry',
    'jobs.savedJobs': 'Uložené práce',
    'jobs.placeholder': 'Hledat podle pozice, firmy nebo dovedností...',
    'jobs.newMatch': 'Nová shoda',
    'jobs.matchLabel': 'Shoda',
    'jobs.quickFilters': 'Rychlé filtry',
    'jobs.clear': 'Smazat',
    'jobs.verifiedEmployers': 'Ověření zaměstnavatelé',
    'jobs.vettedDesc': 'Každá firma je ručně prověřena, abychom zajistili, že si váží vaší sportovní minulosti.',
    'browse.title': 'Databáze sportovců',
    'browse.subtitle': 'Najděte kandidáty s disciplínou a vytrvalostí elitních sportovců.',
    'browse.premiumAccess': 'Prémiový přístup k talentům',
    'browse.postJob': 'Vložit pozici',
    'browse.searchPlaceholder': 'Hledat podle jména, sportu nebo dovedností...',
    'browse.searchBtn': 'Hledat kandidáty',
    'browse.filters': 'Filtry',
    'browse.reset': 'Resetovat',
    'browse.sportingLevel': 'Sportovní úroveň',
    'browse.availability': 'Dostupnost',
    'browse.verifiedAthletes': 'Ověření sportovci',
    'browse.verifiedDesc': 'Historie každého kandidáta je naším týmem ručně ověřena.',
    'browse.matchScore': 'Shoda',
    'browse.topTalent': 'Top Talent',
    'browse.viewProfile': 'Zobrazit profil',
    'browse.upgradeTitle': 'Upgradujte pro přístup k dalším talentům',
    'browse.upgradeDesc': 'Váš plán zobrazuje pouze top talenty. Získejte přístup k celé databázi.',
    'browse.upgradeBtn': 'Upgradovat plán',
    'employers.hiringComplete': 'Nábor dokončen',
    'employers.findingCandidates': 'Najděte kandidáty, kteří vědí, co je skutečný výkon',
    'employers.winningMentality': 'Sportovci trénují roky, aby dosáhli špičkových výsledků. Přiveďte tuhle vítěznou mentalitu do své firmy.',
    'employers.quickInteg': 'Rychlá integrace',
    'employers.quickIntegDesc': 'Naše platforma se propojí s vaším stávajícím HR procesem během jediného dne.',
    'employers.dataAnal': 'Datová analýza',
    'employers.dataAnalDesc': 'Sledujte metriky svých inzerátů a kvalitu kandidátů v reálném čase přes přehledný dashboard.',
  },
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.athletes': 'For Athletes',
    'nav.employers': 'For Employers',
    'nav.pricing': 'Pricing',
    'nav.contact': 'Contact',
    'nav.blog': 'Stories',
    'nav.login': 'Log in',
    'nav.signup': 'Sign up',

    // Hero
    'hero.headline': '98% of Czech athletes will never go pro.',
    'hero.headline2': 'We give them a career restart.',
    'hero.subheadline': 'The first job portal in the Czech Republic connecting athletic talent with real career opportunities.',
    'hero.cta.athlete': 'Create profile for free',
    'hero.cta.employer': 'Find athletic talents',

    // Story section
    'story.title': 'When sport ends, life doesn\'t.',
    'story.paragraph1': 'Tomáš trained six days a week. An injury decided for him.',
    'story.paragraph2': 'Eliška led her team as captain. After her career, she heard she "lacks experience".',
    'story.paragraph3': 'Talent Restart was created so athletes don\'t have to start from zero.',
    'story.paragraph4': 'Discipline, perseverance, and responsibility have value beyond the stadium.',

    // Pricing
    'pricing.title': 'Pricing for Employers',
    'pricing.subtitle': 'Choose the plan that suits you',
    'pricing.standard': 'Standard Pack',
    'pricing.pro': 'Pro Pack',
    'pricing.monthly': 'monthly',
    'pricing.yearly': 'yearly',
    'pricing.perMonth': 'month',
    'pricing.perYear': 'year',
    'pricing.cta': 'Get started',
    'pricing.features.jobs': 'Unlimited job postings',
    'pricing.features.applicants': 'Access to athlete profiles',
    'pricing.features.ai': 'AI assistant for job descriptions',
    'pricing.features.support': 'Priority support',
    'pricing.features.analytics': 'Advanced analytics',
    'pricing.features.branding': 'Company branding',

    // Contact
    'contact.title': 'Contact Us',
    'contact.subtitle': 'Have a question? We\'re happy to help.',
    'contact.name': 'Full name',
    'contact.email': 'Email',
    'contact.phone': 'Phone',
    'contact.role': 'I am a',
    'contact.role.employer': 'Employer',
    'contact.role.athlete': 'Athlete',
    'contact.role.club': 'Club',
    'contact.role.university': 'University',
    'contact.role.other': 'Other',
    'contact.organization': 'Organization name',
    'contact.subject': 'Subject',
    'contact.subject.hiring': 'Hiring',
    'contact.subject.partnership': 'Partnership',
    'contact.subject.support': 'Support',
    'contact.subject.general': 'General inquiry',
    'contact.message': 'Message',
    'contact.gdpr': 'I agree to the processing of personal data',
    'contact.submit': 'Send message',
    'contact.success': 'Thank you for your message. We will get back to you soon.',

    // Login
    'login.subtitle': 'Sign in to your account',
    'login.email': 'Email',
    'login.password': 'Password',
    'login.submit': 'Log in',
    'login.noAccount': 'Don\'t have an account?',
    'login.signupLink': 'Sign up',

    // Signup
    'signup.subtitle': 'Create a new account',
    'signup.athlete': 'Athlete',
    'signup.employer': 'Employer',
    'signup.firstName': 'First name',
    'signup.lastName': 'Last name',
    'signup.email': 'Email',
    'signup.password': 'Password',
    'signup.confirmPassword': 'Confirm password',
    'signup.submitAthlete': 'Create athlete profile',
    'signup.submitEmployer': 'Create employer account',
    'signup.hasAccount': 'Already have an account?',
    'signup.loginLink': 'Log in',

    // Footer
    'footer.rights': 'All rights reserved.',


    // Theme
    'theme.light': 'Day mode',
    'theme.dark': 'Night mode',

    // Dashboard
    'dash.header': 'Dashboard',
    'dash.premium': 'Premium Active',
    'dash.demand': 'Market High Demand',
    'dash.session': 'Session',
    'dash.proAccount': 'Pro Account',
    'dash.freeAccount': 'Free Account',
    'dash.availableAthletes': 'Available Athletes',
    'dash.missedOps': 'Missed Opportunities',
    'dash.compsFaster': 'Competitors are faster.',
    'dash.advAnalytics': 'Advanced Analytics',
    'dash.premAnalytics': 'Premium Analytics',
    'dash.unlockData': 'Unlock Data',
    'dash.viewReports': 'View Reports',
    'dash.recommendations': 'Top Recommendations',
    'dash.viewAll': 'View All',
    'dash.recRisk': 'Recruitment Risk',
    'dash.high': 'HIGH',
    'dash.riskDesc': 'Your current "Passive" strategy has a 80% failure rate in this market.',
    'dash.marketSpeed': 'Market Speed',
    'dash.critical': 'Critical',
    'dash.strategyActive': 'Strategy Active',
    'dash.switchAggressive': 'Switch to Aggressive',
    'dash.missingPotential': 'You are missing 85% of candidates.',
    'dash.upgradeNow': 'Upgrade Now',
    'dash.limit': 'Free Plan Limit',
    'dash.overview': 'Overview',
    'dash.pipeline': 'Talent Pipeline',
    'dash.messages': 'Messages',
    'dash.history': 'History',
    'dash.marketIntel': 'Market Intelligence',
    'dash.compWatch': 'Competitor Watch',
    'dash.riskAnalysis': 'Risk Analysis',
    'dash.nextSteps': 'Your Next Steps',
    'dash.completeCv': 'Complete CV',
    'dash.addAchiev': 'Add your achievements',
    'dash.aiTrans': 'AI Translation',
    'dash.convSkills': 'Convert sports skills',
    'dash.browseJobs': 'Browse Jobs',
    'dash.newMatches': '3 new matches',
    'dash.recReads': 'Recommended Reads',
    'dash.mostPop': 'Most Popular',
    'dash.futureLeader': 'Future Business Leader',
    'dash.profileStr': 'Profile Strength',
    'dash.topCandidate': 'You are in the top 10% of candidates!',
    'dash.proTip': 'Pro Tip',
    'dash.proTipDesc': '"In business, like in sports, recovery is key. Don\'t burnout before the interview phase."',
    'dash.readMore': 'Read More',
    'header.myCareer': 'My Career',
    'header.overview': 'Overview',
    'header.careerTips': 'Career Tips',
    'header.loggedInAs': 'Logged in as',
    'header.myProfile': 'My Profile',
    'header.logout': 'Logout',
    'footer.athletes': 'For Athletes',
    'footer.createProfile': 'Create Profile',
    'footer.careerAdvice': 'Career Advice',
    'footer.athleteStories': 'Athlete Stories',
    'footer.employers': 'For Companies',
    'footer.businessSolutions': 'Business Solutions',
    'footer.contact': 'Contact',
    'footer.location': 'Prague, Czech Republic',
    'footer.desc': 'The first platform in CZ connecting athlete discipline with business world opportunities.',
    'index.hero.athletePath': 'Your Career Path',
    'index.hero.welcomeBack': 'Welcome back',
    'index.hero.nextChallenge': 'Your next challenge awaits',
    'index.hero.discoverTalents': 'Discover more talents',
    'index.hero.strength': 'Profile Strength',
    'index.hero.newMatches': 'New Matches',
    'index.hero.views': 'Views',
    'index.howItWorks': 'How it Works',
    'index.simpleProcess': 'Simple process for both athletes and employers',
    'index.successStories': 'Success Stories',
    'index.storyDesc': 'Be inspired by athletes who have already successfully managed their restart.',
    'index.allStories': 'All stories',
    'index.readyStart': 'Ready for a new start?',
    'index.joinThousands': 'Join thousands of athletes who found new careers through Talent Restart.',
    'athletes.hero.newStart': 'Your new start',
    'athletes.hero.careerValue': 'Your athletic career',
    'athletes.hero.enormousValue': 'has enormous value',
    'athletes.whyRestart': 'Why choose Talent Restart?',
    'athletes.notJustCv': "With us you don't just write a CV, you tell the story of your success.",
    'athletes.medals': "We can't display your medals.",
    'athletes.translate': "But we can translate them.",
    'athletes.aiDesc': 'Our advanced AI algorithm analyzes your sports history and automatically transforms it into a language that HR managers and CEOs understand.',
    'athletes.beta': 'Try AI Assistant (Beta)',
    'pricing.transparent': 'Transparent Pricing',
    'pricing.athletesFree': 'Athletes always get 100% FREE access',
    'pricing.popular': 'Most Popular',
    'pricing.noFees': 'No hidden fees',
    'pricing.secure': 'Secure payments',
    'pricing.support': 'Top support',
    'pricing.instant': 'Instant access',
    'pricing.fair': 'Fair conditions',
    'jobs.browse': 'Search Jobs',
    'jobs.matches': 'Matches',
    'jobs.multiplier': 'Positions where your sports discipline acts as a multiplier.',
    'jobs.filters': 'Filters',
    'jobs.savedJobs': 'Saved Jobs',
    'jobs.placeholder': 'Search by role, company or skills...',
    'jobs.newMatch': 'New Match',
    'jobs.matchLabel': 'Match',
    'jobs.quickFilters': 'Quick Filters',
    'jobs.clear': 'Clear',
    'jobs.verifiedEmployers': 'Verified Employers',
    'jobs.vettedDesc': 'Every company is manually vetted to ensure they value your sports background.',
    'browse.title': 'Athlete Database',
    'browse.subtitle': 'Find candidates with the discipline and grit of elite athletes.',
    'browse.premiumAccess': 'Premium Talent Access',
    'browse.postJob': 'Post New Job',
    'browse.searchPlaceholder': 'Search by name, sport or professional skill...',
    'browse.searchBtn': 'Search Candidates',
    'browse.filters': 'Filters',
    'browse.reset': 'Reset',
    'browse.sportingLevel': 'Sporting Level',
    'browse.availability': 'Availability',
    'browse.verifiedAthletes': 'Verified Athletes',
    'browse.verifiedDesc': 'Every candidate\'s sports history is verified by our team.',
    'browse.matchScore': 'Match Score',
    'browse.topTalent': 'Top Talent',
    'browse.viewProfile': 'View Profile',
    'browse.upgradeTitle': 'Upgrade to Unlock More Talent',
    'browse.upgradeDesc': 'Your plan only shows top performers. Gain full access to our database.',
    'browse.upgradeBtn': 'Upgrade Plan',
    'employers.hiringComplete': 'Hiring completed',
    'employers.findingCandidates': 'Find candidates who know what true performance means',
    'employers.winningMentality': 'Athletes train for years for peak performance. Bring that winning mentality to your company.',
    'employers.quickInteg': 'Quick Integration',
    'employers.quickIntegDesc': 'Our platform connects with your existing HR process in a single day.',
    'employers.dataAnal': 'Data Analysis',
    'employers.dataAnalDesc': 'Track your ad metrics and candidate quality in real time via a clear dashboard.',
  },
  de: {
    // Navigation
    'nav.home': 'Startseite',
    'nav.athletes': 'Für Sportler',
    'nav.employers': 'Für Arbeitgeber',
    'nav.pricing': 'Preise',
    'nav.contact': 'Kontakt',
    'nav.blog': 'Geschichten',
    'nav.login': 'Anmelden',
    'nav.signup': 'Registrieren',

    // Hero
    'hero.headline': '98% der tschechischen Sportler werden nie Profis.',
    'hero.headline2': 'Wir geben ihnen einen Karriere-Neustart.',
    'hero.subheadline': 'Das erste Jobportal in der Tschechischen Republik, das sportliche Talente mit echten Karrieremöglichkeiten verbindet.',
    'hero.cta.athlete': 'Profil kostenlos erstellen',
    'hero.cta.employer': 'Sportliche Talente finden',

    // Story section
    'story.title': 'Wenn der Sport endet, endet das Leben nicht.',
    'story.paragraph1': 'Tomáš trainierte sechs Tage die Woche. Eine Verletzung entschied für ihn.',
    'story.paragraph2': 'Eliška führte ihr Team als Kapitänin. Nach ihrer Karriere hörte sie, dass sie "keine Erfahrung" habe.',
    'story.paragraph3': 'Talent Restart wurde geschaffen, damit Sportler nicht bei null anfangen müssen.',
    'story.paragraph4': 'Disziplin, Ausdauer und Verantwortung haben auch jenseits des Stadions Wert.',

    // Pricing
    'pricing.title': 'Preise für Arbeitgeber',
    'pricing.subtitle': 'Wählen Sie den Plan, der zu Ihnen passt',
    'pricing.standard': 'Standard Paket',
    'pricing.pro': 'Pro Paket',
    'pricing.monthly': 'monatlich',
    'pricing.yearly': 'jährlich',
    'pricing.perMonth': 'Monat',
    'pricing.perYear': 'Jahr',
    'pricing.cta': 'Jetzt starten',
    'pricing.features.jobs': 'Unbegrenzte Stellenanzeigen',
    'pricing.features.applicants': 'Zugang zu Sportlerprofilen',
    'pricing.features.ai': 'KI-Assistent für Stellenbeschreibungen',
    'pricing.features.support': 'Prioritäts-Support',
    'pricing.features.analytics': 'Erweiterte Analytik',
    'pricing.features.branding': 'Firmen-Branding',

    // Contact
    'contact.title': 'Kontaktieren Sie uns',
    'contact.subtitle': 'Haben Sie eine Frage? Wir helfen Ihnen gerne.',
    'contact.name': 'Vollständiger Name',
    'contact.email': 'E-Mail',
    'contact.phone': 'Telefon',
    'contact.role': 'Ich bin',
    'contact.role.employer': 'Arbeitgeber',
    'contact.role.athlete': 'Sportler',
    'contact.role.club': 'Verein',
    'contact.role.university': 'Universität',
    'contact.role.other': 'Sonstiges',
    'contact.organization': 'Name der Organisation',
    'contact.subject': 'Betreff',
    'contact.subject.hiring': 'Einstellung',
    'contact.subject.partnership': 'Partnerschaft',
    'contact.subject.support': 'Support',
    'contact.subject.general': 'Allgemeine Anfrage',
    'contact.message': 'Nachricht',
    'contact.gdpr': 'Ich stimme der Verarbeitung personenbezogener Daten zu',
    'contact.submit': 'Nachricht senden',
    'contact.success': 'Vielen Dank für Ihre Nachricht. Wir werden uns bald bei Ihnen melden.',

    // Login
    'login.subtitle': 'Melden Sie sich bei Ihrem Konto an',
    'login.email': 'E-Mail',
    'login.password': 'Passwort',
    'login.submit': 'Anmelden',
    'login.noAccount': 'Noch kein Konto?',
    'login.signupLink': 'Registrieren',

    // Signup
    'signup.subtitle': 'Erstellen Sie ein neues Konto',
    'signup.athlete': 'Sportler',
    'signup.employer': 'Arbeitgeber',
    'signup.firstName': 'Vorname',
    'signup.lastName': 'Nachname',
    'signup.email': 'E-Mail',
    'signup.password': 'Passwort',
    'signup.confirmPassword': 'Passwort bestätigen',
    'signup.submitAthlete': 'Sportlerprofil erstellen',
    'signup.submitEmployer': 'Arbeitgeberkonto erstellen',
    'signup.hasAccount': 'Bereits ein Konto?',
    'signup.loginLink': 'Anmelden',

    // Footer
    'footer.rights': 'Alle Rechte vorbehalten.',


    // Theme
    'theme.light': 'Tagmodus',
    'theme.dark': 'Nachtmodus',

    // Dashboard
    'dash.header': 'Dashboard',
    'dash.premium': 'Premium Aktiv',
    'dash.demand': 'Hohe Marktnachfrage',
    'dash.session': 'Sitzung',
    'dash.proAccount': 'Pro Konto',
    'dash.freeAccount': 'Kostenloses Konto',
    'dash.availableAthletes': 'Verfügbare Sportler',
    'dash.missedOps': 'Verpasste Gelegenheiten',
    'dash.compsFaster': 'Die Konkurrenz ist schneller.',
    'dash.advAnalytics': 'Erweiterte Analytik',
    'dash.premAnalytics': 'Premium Analytik',
    'dash.unlockData': 'Daten freischalten',
    'dash.viewReports': 'Berichte anzeigen',
    'dash.recommendations': 'Top-Empfehlungen',
    'dash.viewAll': 'Alle anzeigen',
    'dash.recRisk': 'Einstellungsrisiko',
    'dash.high': 'HOCH',
    'dash.riskDesc': 'Ihre aktuelle "passive" Strategie hat in diesem Markt eine Fehlerquote von 80%.',
    'dash.marketSpeed': 'Marktgeschwindigkeit',
    'dash.critical': 'Kritisch',
    'dash.strategyActive': 'Strategie aktiv',
    'dash.switchAggressive': 'Auf aggressiv umschalten',
    'dash.missingPotential': 'Sie verpassen 85 % der Kandidaten.',
    'dash.upgradeNow': 'Jetzt upgraden',
    'dash.limit': 'Limit für kostenlosen Plan',
    'dash.overview': 'Übersicht',
    'dash.pipeline': 'Talent Pipeline',
    'dash.messages': 'Nachrichten',
    'dash.history': 'Verlauf',
    'dash.marketIntel': 'Marktintelligenz',
    'dash.compWatch': 'Wettbewerbsbeobachtung',
    'dash.riskAnalysis': 'Risikoanalyse',
    'dash.nextSteps': 'Ihre nächsten Schritte',
    'dash.completeCv': 'Lebenslauf vervollständigen',
    'dash.addAchiev': 'Fügen Sie Ihre Erfolge hinzu',
    'dash.aiTrans': 'KI-Übersetzung',
    'dash.convSkills': 'Sportliche Fähigkeiten umwandeln',
    'dash.browseJobs': 'Jobs durchsuchen',
    'dash.newMatches': '3 neue Treffer',
    'dash.recReads': 'Empfohlene Lektüre',
    'dash.mostPop': 'Beliebteste',
    'dash.futureLeader': 'Zukünftiger Business Leader',
    'dash.profileStr': 'Profilstärke',
    'dash.topCandidate': 'Sie gehören zu den Top 10 % der Kandidaten!',
    'dash.proTip': 'Pro-Tipp',
    'dash.proTipDesc': '"Im Business ist es wie im Sport: Erholung ist der Schlüssel. Brennen Sie nicht vor der Interviewphase aus."',
    'dash.readMore': 'Weiterlesen',
    'header.myCareer': 'Meine Karriere',
    'header.overview': 'Übersicht',
    'header.careerTips': 'Karriere-Tipps',
    'header.loggedInAs': 'Angemeldet als',
    'header.myProfile': 'Mein Profil',
    'header.logout': 'Abmelden',
    'footer.athletes': 'Für Sportler',
    'footer.createProfile': 'Profil erstellen',
    'footer.careerAdvice': 'Karriereberatung',
    'footer.athleteStories': 'Sportlergeschichten',
    'footer.employers': 'Für Unternehmen',
    'footer.businessSolutions': 'Business-Lösungen',
    'footer.contact': 'Kontakt',
    'footer.location': 'Prag, Tschechische Republik',
    'footer.desc': 'Die erste Plattform in CZ, die die Disziplin von Sportlern mit Möglichkeiten in der Geschäftswelt verbindet.',
    'index.hero.athletePath': 'Ihr Karriereweg',
    'index.hero.welcomeBack': 'Willkommen zurück',
    'index.hero.nextChallenge': 'Ihre nächste Herausforderung wartet',
    'index.hero.discoverTalents': 'Entdecken Sie weitere Talente',
    'index.hero.strength': 'Profilstärke',
    'index.hero.newMatches': 'Neue Treffer',
    'index.hero.views': 'Ansichten',
    'index.howItWorks': 'Wie es funktioniert',
    'index.simpleProcess': 'Einfacher Prozess für Sportler und Arbeitgeber',
    'index.successStories': 'Erfolgsgeschichten',
    'index.storyDesc': 'Lassen Sie sich von Sportlern inspirieren, die ihren Neustart bereits erfolgreich gemeistert haben.',
    'index.allStories': 'Alle Geschichten',
    'index.readyStart': 'Bereit für einen Neuanfang?',
    'index.joinThousands': 'Schließen Sie sich Tausenden von Sportlern an, die dank Talent Restart eine neue Karriere gefunden haben.',
    'athletes.hero.newStart': 'Ihr Neuanfang',
    'athletes.hero.careerValue': 'Ihre sportliche Karriere',
    'athletes.hero.enormousValue': 'hat einen enormen Wert',
    'athletes.whyRestart': 'Warum Talent Restart wählen?',
    'athletes.notJustCv': 'Bei uns schreiben Sie nicht nur einen Lebenslauf, Sie erzählen die Geschichte Ihres Erfolgs.',
    'athletes.medals': 'Wir können Ihre Medaillen nicht ausstellen.',
    'athletes.translate': 'Aber wir können sie übersetzen.',
    'athletes.aiDesc': 'Unser fortschrittlicher KI-Algorithmus analysiert Ihre Sportgeschichte und transformiert sie automatisch in eine Sprache, die HR-Manager und CEOs verstehen.',
    'athletes.beta': 'KI-Assistent ausprobieren (Beta)',
    'pricing.transparent': 'Transparente Preise',
    'pricing.athletesFree': 'Sportler haben immer 100% KOSTENLOSEN Zugang',
    'pricing.popular': 'Beliebteste',
    'pricing.noFees': 'Keine versteckten Gebühren',
    'pricing.secure': 'Sichere Zahlungen',
    'pricing.support': 'Top-Unterstützung',
    'pricing.instant': 'Sofortiger Zugriff',
    'pricing.fair': 'Faire Bedingungen',
    'jobs.browse': 'Jobs suchen',
    'jobs.matches': 'Treffer',
    'jobs.multiplier': 'Positionen, in denen Ihre sportliche Disziplin als Multiplikator wirkt.',
    'jobs.filters': 'Filter',
    'jobs.savedJobs': 'Gespeicherte Jobs',
    'jobs.placeholder': 'Suche nach Rolle, Firma oder Fähigkeiten...',
    'jobs.newMatch': 'Neuer Treffer',
    'jobs.matchLabel': 'Treffer',
    'jobs.quickFilters': 'Schnellfilter',
    'jobs.clear': 'Löschen',
    'jobs.verifiedEmployers': 'Verifizierte Arbeitgeber',
    'jobs.vettedDesc': 'Jedes Unternehmen wird manuell geprüft, um sicherzustellen, dass es Ihren sportlichen Hintergrund schätzt.',
    'browse.title': 'Athleten-Datenbank',
    'browse.subtitle': 'Finden Sie Kandidaten mit der Disziplin und Ausdauer von Elitesportlern.',
    'browse.premiumAccess': 'Premium-Talent-Zugang',
    'browse.postJob': 'Neue Stelle posten',
    'browse.searchPlaceholder': 'Suche nach Name, Sportart oder beruflichen Fähigkeiten...',
    'browse.searchBtn': 'Kandidaten suchen',
    'browse.filters': 'Filter',
    'browse.reset': 'Zurücksetzen',
    'browse.sportingLevel': 'Sportliches Niveau',
    'browse.availability': 'Verfügbarkeit',
    'browse.verifiedAthletes': 'Verifizierte Athleten',
    'browse.verifiedDesc': 'Die Sporthistorie jedes Kandidaten wird von unserem Team verifiziert.',
    'browse.matchScore': 'Match-Score',
    'browse.topTalent': 'Top-Talent',
    'browse.viewProfile': 'Profil anzeigen',
    'browse.upgradeTitle': 'Upgrade für mehr Talente',
    'browse.upgradeDesc': 'Ihr Plan zeigt nur Top-Performer. Erhalten Sie vollen Zugriff.',
    'browse.upgradeBtn': 'Plan upgraden',
    'employers.hiringComplete': 'Rekrutierung abgeschlossen',
    'employers.findingCandidates': 'Finden Sie Kandidaten, die wissen, was echte Leistung bedeutet',
    'employers.winningMentality': 'Sportler trainieren jahrelang für Höchstleistungen. Bringen Sie diese Gewinnermentalität in Ihr Unternehmen.',
    'employers.quickInteg': 'Schnelle Integration',
    'employers.quickIntegDesc': 'Unsere Plattform lässt sich an einem Tag in Ihren bestehenden HR-Prozess integrieren.',
    'employers.dataAnal': 'Datenanalyse',
    'employers.dataAnalDesc': 'Verfolgen Sie Ihre Anzeigenmetriken und Kandidatenqualität in Echtzeit über ein übersichtliches Dashboard.',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>('cs');

  // Currency is strictly tied to language
  const currency: Currency = language === 'cs' ? 'CZK' : 'EUR';

  useEffect(() => {
    const savedLang = localStorage.getItem('language') as Language;
    if (savedLang && ['cs', 'en', 'de'].includes(savedLang)) {
      setLanguageState(savedLang);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, currency, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
